import { describe, it, expect, beforeEach } from 'vitest';
import fc from 'fast-check';

/**
 * Property 2: Video Thumbnail Store Round-Trip
 *
 * For any valid video item ID and any data URL string, storing the thumbnail
 * via setVideoThumbnail(id, dataUrl) and then retrieving via getVideoThumbnail(id)
 * SHALL return the original data URL. Furthermore, serializing the entire
 * video_thumbnails store to JSON and deserializing SHALL produce an equivalent object.
 *
 * **Validates: Requirements 2.2, 2.5**
 * Feature: media-and-editor-upgrades, Property 2: Video Thumbnail Store Round-Trip
 */

// --- localStorage mock ---

function createMockLocalStorage() {
  const store = {};
  return {
    getItem(key) {
      return Object.prototype.hasOwnProperty.call(store, key) ? store[key] : null;
    },
    setItem(key, value) {
      store[key] = String(value);
    },
    removeItem(key) {
      delete store[key];
    },
    clear() {
      for (const k of Object.keys(store)) {
        delete store[k];
      }
    },
  };
}

let mockLocalStorage;

// --- Re-implement the functions under test (matching script.js logic exactly) ---

const VIDEO_THUMBNAIL_STORAGE_KEY = 'video_thumbnails';

function getVideoThumbnail(itemId) {
  try {
    var raw = mockLocalStorage.getItem(VIDEO_THUMBNAIL_STORAGE_KEY);
    var store = raw ? JSON.parse(raw) : {};
    return Object.prototype.hasOwnProperty.call(store, itemId) ? store[itemId] : null;
  } catch (e) {
    return null;
  }
}

function setVideoThumbnail(itemId, dataUrl) {
  try {
    var raw = mockLocalStorage.getItem(VIDEO_THUMBNAIL_STORAGE_KEY);
    var store = raw ? JSON.parse(raw) : {};
    store[itemId] = dataUrl;
    mockLocalStorage.setItem(VIDEO_THUMBNAIL_STORAGE_KEY, JSON.stringify(store));
  } catch (e) {
    // Silently fail on localStorage errors
  }
}

// --- Arbitraries ---

/**
 * Generate a valid video item ID (non-empty alphanumeric + dashes/underscores).
 * Excludes prototype-polluting keys like __proto__, constructor, toString since
 * real item IDs are generated by MediaManager (e.g., "media_1716000000000").
 */
const RESERVED_KEYS = ['__proto__', 'constructor', 'toString', 'valueOf', 'hasOwnProperty'];
const itemIdArb = fc
  .stringMatching(/^[a-zA-Z0-9_-]+$/, { minLength: 1, maxLength: 40 })
  .filter((id) => !RESERVED_KEYS.includes(id));

/** Generate a data URL string (mimics base64-encoded image data URLs) */
const dataUrlArb = fc.oneof(
  // Realistic data URLs
  fc.tuple(
    fc.constantFrom('image/png', 'image/jpeg', 'image/webp'),
    fc.base64String({ minLength: 4, maxLength: 200 })
  ).map(([mime, data]) => `data:${mime};base64,${data}`),
  // Arbitrary non-empty strings (the store doesn't validate format)
  fc.string({ minLength: 1, maxLength: 300 })
);

// --- Property Tests ---

describe('Feature: media-and-editor-upgrades, Property 2: Video Thumbnail Store Round-Trip', () => {
  beforeEach(() => {
    mockLocalStorage = createMockLocalStorage();
  });

  it('storing and retrieving a thumbnail returns the original data URL', () => {
    /**
     * Validates: Requirements 2.2
     *
     * For any valid item ID and any data URL string, setVideoThumbnail followed
     * by getVideoThumbnail SHALL return the exact same data URL.
     */
    fc.assert(
      fc.property(
        itemIdArb,
        dataUrlArb,
        (itemId, dataUrl) => {
          mockLocalStorage.clear();

          setVideoThumbnail(itemId, dataUrl);
          const retrieved = getVideoThumbnail(itemId);

          expect(retrieved).toBe(dataUrl);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('multiple thumbnails can be stored and retrieved independently', () => {
    /**
     * Validates: Requirements 2.2
     *
     * For any two distinct item IDs and their respective data URLs,
     * storing both and retrieving each SHALL return the correct data URL.
     */
    fc.assert(
      fc.property(
        itemIdArb,
        itemIdArb,
        dataUrlArb,
        dataUrlArb,
        (id1, id2, url1, url2) => {
          fc.pre(id1 !== id2);
          mockLocalStorage.clear();

          setVideoThumbnail(id1, url1);
          setVideoThumbnail(id2, url2);

          expect(getVideoThumbnail(id1)).toBe(url1);
          expect(getVideoThumbnail(id2)).toBe(url2);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('retrieving a non-existent thumbnail returns null', () => {
    /**
     * Validates: Requirements 2.2
     *
     * For any item ID that has not been stored, getVideoThumbnail SHALL return null.
     */
    fc.assert(
      fc.property(
        itemIdArb,
        (itemId) => {
          mockLocalStorage.clear();

          const retrieved = getVideoThumbnail(itemId);
          expect(retrieved).toBeNull();
        }
      ),
      { numRuns: 100 }
    );
  });

  it('JSON serialization/deserialization of the store produces an equivalent object', () => {
    /**
     * Validates: Requirements 2.5
     *
     * For any set of item ID / data URL pairs, the video_thumbnails store
     * serialized to JSON and deserialized SHALL produce an equivalent object.
     */
    fc.assert(
      fc.property(
        fc.array(fc.tuple(itemIdArb, dataUrlArb), { minLength: 0, maxLength: 20 }),
        (entries) => {
          mockLocalStorage.clear();

          // Store all entries
          for (const [id, url] of entries) {
            setVideoThumbnail(id, url);
          }

          // Read the raw JSON from localStorage
          const raw = mockLocalStorage.getItem(VIDEO_THUMBNAIL_STORAGE_KEY);

          if (entries.length === 0) {
            // Nothing stored yet
            expect(raw).toBeNull();
            return;
          }

          expect(raw).not.toBeNull();

          // Serialize then deserialize
          const parsed = JSON.parse(raw);
          const reserialized = JSON.stringify(parsed);
          const reparsed = JSON.parse(reserialized);

          // The round-trip should produce an equivalent object
          expect(reparsed).toEqual(parsed);

          // Additionally, each entry should be retrievable
          // (last write wins for duplicate IDs)
          const expectedStore = {};
          for (const [id, url] of entries) {
            expectedStore[id] = url;
          }
          expect(parsed).toEqual(expectedStore);
        }
      ),
      { numRuns: 100 }
    );
  });

  it('overwriting a thumbnail updates the stored value', () => {
    /**
     * Validates: Requirements 2.2
     *
     * For any item ID and two different data URLs, storing the second URL
     * SHALL overwrite the first, and getVideoThumbnail SHALL return the second.
     */
    fc.assert(
      fc.property(
        itemIdArb,
        dataUrlArb,
        dataUrlArb,
        (itemId, url1, url2) => {
          mockLocalStorage.clear();

          setVideoThumbnail(itemId, url1);
          setVideoThumbnail(itemId, url2);

          expect(getVideoThumbnail(itemId)).toBe(url2);
        }
      ),
      { numRuns: 100 }
    );
  });
});
